module.exports = [
  {
    title: 'Black Panther',
    stars: 5,
    writer:"Ryan Coogler",
    starring:['Chadwick Boseman','Michael B. Jordan','Andy Serkis','Danai Gurira','Letitia Wright'],
    img:['/img/black-panther1.jpeg','/img/black-panther2.jpeg'],
    catigory:['superhero','action','adventure'],
    runtime:134,
    movieDescription:"Black Panther is a 2018 American superhero film based on the Marvel Comics character of the same name. Produced by Marvel Studios and distributed by Walt Disney Studios Motion Pictures, it is the eighteenth film in the Marvel Cinematic Universe (MCU). Black panther tells the tail T'Challa apon his return to wankanda and his fight for the thone and mantle of black panther",
    year:2018,
    rated:'PG-13'
  },
  {
    title: 'The Godfather',
    stars: 5,
    writer:"Francis Ford Coppola",
    starring:['Marlon Brando','Al Pacino','James Caan','Diane Keaton'],
    img:['/img/the-godfather1.jpeg','/img/the-godfather2.jpeg'],
    catigory:['crime','drama'],
    runtime:175,
    movieDescription:"The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    year:1972,
    rated:'R'
  },
  {
    title: 'The Shawshank Redemption',
    stars: 4,
    writer:"Frank Darabont",
    starring:['Tim Robbins','Morgan Freeman','Bob Gunton'],
    img:['/img/shawshank1.jpeg','/img/shawshank2.jpeg'],
    catigory:['drama'],
    runtime:142,
    movieDescription:"Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    year:1994,
    rated:'R'
  },
  {
    title: 'Mad Max: Fury Road',
    stars: 4,
    writer:"George Miller",
    starring:['Tom Hardy', 'Charlize Theron', 'Nicholas Hoult',' Zoë Kravitz'],
    img:['/img/madmax1.jpeg','/img/madmax2.jpeg'],
    catigory:['action','adventure','sci-fi'],
    runtime:120,
    movieDescription:"In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.",
    year:2015,
    rated:'R'
  },
  {
    title: 'E.T. The Extra-Terrestrial',
    stars: 3,
    writer:"Steven Spielberg",
    starring:['Henry Thoman','Drew Barrymore','Dee Wallace'],
    img:['/img/et1.jpeg','/img/et2.jpeg'],
    catigory:['family','sci-fi'],
    runtime:115,
    movieDescription:"A troubled child summons the courage to help a friendly alien escape Earth and return to his home world.",
    year:1982,
    rated:'PG'
  },
  {
    title: 'The Lord of the Rings',
    stars: 4,
    writer:"Peter Jackson",
    starring:['Elijah Wood','Viggo Mortensen','Ian McKellen','Orlando Bloom'],
    img:['/img/lotr1.jpeg','/img/lotr2.jpeg'],
    catigory:['adventure','drama','fantasy','action'],
    runtime:201,
    movieDescription:"Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
    year:2003,
    rated:'PG-13'
  },
  {
    title: 'Inside Out',
    stars: 2,
    writer:"Peter Docter",
    starring:['Amy Poehler', 'Bill Hader', 'Lewis Black', 'Mindy Kaling'],
    img:['/img/inside-out1.jpeg','/img/inside-out2.jpeg'],
    catigory:['animation','comedy','disney'],
    runtime:95,
    movieDescription:"After young Riley is uprooted from her Midwest life and moved to San Francisco, her emotions - Joy, Fear, Anger, Disgust and Sadness - conflict on how best to navigate a new city, house, and school.",
    year:2015,
    rated:'PG'
  },
  {
    title: 'Titanic',
    stars: 4,
    writer:"James Cameron",
    starring:['Leonardo DiCaprio', 'Kate Winslet', 'Billy Zane', 'Kathy Bates'],
    img:['/img/titanic1.jpeg','/img/titanic2.jpeg'],
    catigory:['drama','romance'],
    runtime:194,
    movieDescription:"A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.",
    year:1997,
    rated:'PG-13'
  },
  {
    title: 'Gladiator',
    stars: 3,
    writer:"Ridley Scott",
    starring:['Russel Crowe',' Joaquin Phoenix','Connie Nielsen','Oliver Reed'],
    img:['/img/gladiator1.jpeg','/img/gladiator2.jpeg'],
    catigory:['adventure','drama','action'],
    runtime:155,
    movieDescription:"A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
    year:2000,
    rated:'R'
  },
  {
    title: 'Fantastic Beasts and Where to Find Them',
    stars:3,
    writer:'J. K. Rowling',
    starring:['Eddie Redmayne','Dan Fogler','Colin Farrell'],
    img:['/img/fantastic-beast1.jpeg','/img/fantastic-beast2.jpeg'],
    catigory:['magic','action','adventure','mystery'],
    runtime:133,
    movieDescription: "A spinoff of harry potterm, based on the text-book 'fantastic beast and where to find them' that appears throughout the harrypotter series",
    year: 2016,
    rated:"PG-13"
  }
]
